### ISSUE TITLE
paraglide-js 1.0 release 

### ISSUE THREAD

**Issue by samuelstroschein** [opral/monorepo#1439]
## Tasks

- [x] inlang/monorepo#1607 
- [x] inlang/monorepo#1508 
- [x] inlang/monorepo#1608
- [ ] ~~#1481~~
- [x] inlang/monorepo#1475
- [x] inlang/monorepo#1477
- [x] inlang/monorepo#1518
- [x] inlang/monorepo#1519 
- [x] inlang/monorepo#1567
- [x] inlang/internal#181
- [x] ~~warn if two projects compile into the same output directory~~
- [x] inlang/monorepo#1660
- [x] inlang/monorepo#1552 
- [x] rename `changeLanguageTag` to `setLanguageTag` because confusing
- [x] make languageTag a getter function 
- [x] change `storagePath` to `filePath` 
- [x] add `AvailableLanguageTag` type, see https://github.com/inlang/monorepo/issues/1439#issuecomment-1752122249

## Backlog (After 1.0) release

- [ ] inlang/monorepo#1570 
- [x] inlang/monorepo#1474
- [x] inlang/monorepo#1483
- [ ] nextjs/react RSC and CLIENT environments in one adapter component. both implementations, at least on nextjs, use different state. 
- [ ] add doccs on future optimization: how to change import paths in server environment for specific language

**Comment by samuelstroschein** [comment]
There seems to be a pattern: SPA apps wrap their app in a paraglide component which will trigger re-renders and server-side apps will use i18n routing with a build step plugin

**Comment by samuelstroschein** [comment]
**setLanguageTag seems more intuitive than changeLanguageTag**

in any circumstance, the language tag should be _set_ for following translations function calls

**Comment by samuelstroschein** [comment]
**Messages need options with `{ languageTag }` to be callable outside of rendering tree**

**Comment by samuelstroschein** [comment]
**languageTag must be a getter function to allow context apis**

**Comment by felixhaeberle** [comment]
I already mentioned concerns about our rerendering strategies in conjunction with SPA & we therefore possibly "have things to do" both on client & server. 

@samuelstroschein Does this make the runtime more easy or more complex? And if so, do we need dedicated implementations of server/client for multiple frameworks?

**Comment by samuelstroschein** [comment]
> Does this make the runtime more easy or more complex? And if so, do we need dedicated implementations of server/client for multiple frameworks?

Everything easy peasy 😎 It seems like I can not compile the runtime and instead set the "runtime", which really is just "languageTag", in the ParaglideJSProvider. 

let's see what I find

**Comment by samuelstroschein** [comment]
I feel confident that I nailed the paraglide architecture. 

3 concepts really: 

1. message functions that output text
2. runtime defined by `languageTag()` and `onSetLanguageTag()`
3. adapters that set the runtime

adapting paraglide to any framework or environment is usually 10 lines of code by setting `languageTag()` and defining the side-effect with `onSetLanguageTag()` 

![Uploading CleanShot 2023-10-08 at 17.57.55@2x.png…]()

**Comment by samuelstroschein** [comment]
**TODO: expose an `AvailableLanguageTag` type**


```diff

export default function ParaglideNextAdapter(props: { children: React.ReactNode; lang: string }) {
	setLanguageTag(() => {
-		return serverSideLanguageTag().value as (typeof availableLanguageTags)[number]
+ 		return serverSideLanguageTag().value as AvailableLanguageTag
	})
	return <>{props.children}</>
}
```

**Comment by samuelstroschein** [comment]
Re-confirmation RSC in NextJS 13 is working. The architecture described in ⁠paraglide-js⁠ makes things trivial to implement (once a frameworks quirks are known!) 

https://github.com/inlang/monorepo/assets/35429197/4d3628e2-9730-408f-8cf8-d4878e7158ea

**Comment by samuelstroschein** [comment]
I have to find a better pattern for `setLanguageTag`. Ther must be a `setLanguageTagContext` or similar

<img width="766" alt="CleanShot 2023-10-11 at 14 31 11@2x" src="https://github.com/inlang/monorepo/assets/35429197/596ecc05-2d2c-48d5-8f8d-1d3112c6ef26">

**Comment by samuelstroschein** [comment]
The docs are getting close to finished, see https://github.com/inlang/monorepo/tree/paraglide-js/inlang/source-code/paraglide/paraglide-js. 

A few tasks are left that I should be able to complete today, or latest tomorrow.

**Comment by samuelstroschein** [comment]
Paraglide-JS has been pre-released, see https://github.com/inlang/monorepo/discussions/1464 for testing paraglide-js in your project and leaving feedback.

**Comment by CanRau** [comment]
🥳 fantastic work, this looks very promising 😍 

Curious about pluralization and React support, especially using components within translation string, something like shown in the [i18next docs](https://react.i18next.com/latest/trans-component#using-with-react-components), is there anything on the roadmap?

Also how would I store messages in my database instead of a local file?

Didn't post in the feedback discussion as I haven't tried it out yet 😇

**Comment by samuelstroschein** [comment]
> Curious about pluralization and React support, especially using components within translation string, something like shown in the [i18next docs](https://react.i18next.com/latest/trans-component#using-with-react-components), is there anything on the roadmap?

Pluralization support will come in the near future. The data structure for it already exists but apps in the ecosystem do not support it yet. I can't give an ETA. 

> Also how would I store messages in my database instead of a local file?

You would write a plugin that reads and writes to your database, see https://inlang.com/documentation/build-plugin

**Comment by samuelstroschein** [comment]
paraglide has been released in 1.0
